version: "3.9"
services:
  consul-server:
    image: &consul consul:1.12
    ports:
    - 8080:8080
    - 8400:8400
    - 8600:8600
    - 8600:8600/udp
    command: agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -http-port 8080

  consul-agent:
    image: *consul
    ports:
    - 8500:8500
    depends_on:
    - consul-server
    command: agent -retry-join consul-server -client 0.0.0.0

  consul-demo-0: &consul-demo
    build: .
    image: loshz/consul-demo
    depends_on:
    - consul-agent
    ports:
    - 8001:8001
    command: -id=0 -port=8001
  
  consul-demo-1:
    <<: *consul-demo
    ports:
    - 8002:8002
    command: -id=1 -port=8002

  consul-demo-2:
    <<: *consul-demo
    ports:
    - 8003:8003
    command: -id=2 -port=8003
